# Generated by Django 6.0.1 on 2026-01-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='remaining_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_due',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
