# Generated by Django 6.0.1 on 2026-01-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_collection_remaining_due_alter_loan_principal_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='remaining_due',
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
